{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"XCTFail"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"\")"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional description of the assertion, for inclusion in test"},{"type":"text","text":" "},{"type":"text","text":"results."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Dynamically creates and records an "},{"type":"codeVoice","code":"XCTIssue"},{"type":"text","text":" under the hood that captures the source code"},{"type":"text","text":" "},{"type":"text","text":"context of the caller. Useful for defining assertion helpers that fail in indirect code"},{"type":"text","text":" "},{"type":"text","text":"paths, where the "},{"type":"codeVoice","code":"file"},{"type":"text","text":" and "},{"type":"codeVoice","code":"line"},{"type":"text","text":" of the failure have not been realized."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/xctestdynamicoverlay\/xctfail(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/co.pointfree.ComposableArchitecture\/documentation\/XCTestDynamicOverlay\/XCTFail(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This function generates a failure immediately and unconditionally."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"XCTFail"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"XCTFail(_:)","roleHeading":"Function","role":"symbol","symbolKind":"func","externalID":"s:20XCTestDynamicOverlay7XCTFailyySSF","modules":[{"name":"XCTestDynamicOverlay"}]},"hierarchy":{"paths":[["doc:\/\/co.pointfree.ComposableArchitecture\/documentation\/XCTestDynamicOverlay"]]},"references":{"doc://co.pointfree.ComposableArchitecture/documentation/XCTestDynamicOverlay/XCTFail(_:)":{"role":"symbol","title":"XCTFail(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"XCTFail"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This function generates a failure immediately and unconditionally."}],"identifier":"doc:\/\/co.pointfree.ComposableArchitecture\/documentation\/XCTestDynamicOverlay\/XCTFail(_:)","kind":"symbol","type":"topic","url":"\/documentation\/xctestdynamicoverlay\/xctfail(_:)"},"doc://co.pointfree.ComposableArchitecture/documentation/XCTestDynamicOverlay":{"role":"collection","title":"XCTestDynamicOverlay","abstract":[],"identifier":"doc:\/\/co.pointfree.ComposableArchitecture\/documentation\/XCTestDynamicOverlay","kind":"symbol","type":"topic","url":"\/documentation\/xctestdynamicoverlay"}}}